// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./src/components/Counter.vue')['default']
    ExpandCard: typeof import('./src/components/ExpandCard.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HonorsTabs: typeof import('./src/components/HonorsTabs.vue')['default']
    ImageSwipe: typeof import('./src/components/ImageSwipe.vue')['default']
    ImageSwippe: typeof import('./src/components/ImageSwippe.vue')['default']
    PageTabs: typeof import('./src/components/PageTabs.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Starport: typeof import('vue-starport')['Starport']
    StarportCarrier: typeof import('vue-starport')['StarportCarrier']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCard: typeof import('@varlet/ui')['_CardComponent']
    VarDivider: typeof import('@varlet/ui')['_DividerComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
    VarSwipe: typeof import('@varlet/ui')['_SwipeComponent']
    VarSwipeItem: typeof import('@varlet/ui')['_SwipeItemComponent']
    VarTab: typeof import('@varlet/ui')['_TabComponent']
    VarTabItem: typeof import('@varlet/ui')['_TabItemComponent']
    VarTabs: typeof import('@varlet/ui')['_TabsComponent']
    VarTabsItem: typeof import('@varlet/ui')['_TabsItemComponent']
    VarTabsItems: typeof import('@varlet/ui')['_TabsItemsComponent']
  }
  export interface ComponentCustomProperties {
    vRipple: typeof import('@varlet/ui')['_RippleComponent']
  }
}
